branch-defaults:
  default:
    environment: sg-vaccine-tracker
    group_suffix: null
deploy:
  artifact: ./build/Archive.zip
global:
  application_name: sg-vaccine-tracker
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb
  repository: null
  sc: null
  workspace_type: Application
