# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: api unit tests

defaults:
  run:
    working-directory: ./api

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    - name: Setup DynamoDB local
      uses: rrainn/dynamodb-action@v2.0.0
      with:
        sharedDb: true
        port: 8000

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Configure AWS Credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install serverless
      run: npm i -g serverless
    - name: Migrate the DynamoDB tables
      run: serverless dynamodb migrate --stage local
    - name: Seed DynamoDB tables
      run: serverless dynamodb seed --stage local

    - name: Install NPM dependencies
      run: npm ci

    - name: Run tests
      run: npx jest --runInBand --bail
